### PR TITLE
Add potential to register and use external providers

### PR DESCRIPTION
**Pull request by t-persson**
Add potential to register and use external providers

### CODE REVIEW

**Comment by t-persson** [comment]
Current dependencies on/for this PR:
* main
  * **PR #53** <a href="https://app.graphite.dev/github/pr/eiffel-community/etos-environment-provider/53" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Comment by t-persson** [comment]
Note that this is quite untested. I was going to create a draft PR but fumbled

**Review by fredjn — DISMISSED** [review]

**Review by andjoe-axis — DISMISSED** [review]

**Review by fredjn — APPROVED** [review]

**Review by andjoe-axis — APPROVED** [review]

**Review by nordixinfra — COMMENTED** [review]
- Build Status: **SUCCESS**
- Build URL: [Nordix Jenkins](https://jenkins.nordix.org/job/etos-environment-provider-build-merge-ubuntu2004-main/15/)
- Command to pull image:
    `docker pull registry.nordix.org/eiffel/etos-environment-provider:dev`
    or
    `podman pull registry.nordix.org/eiffel/etos-environment-provider:dev`

**Review by nordixinfra — COMMENTED** [review]
- Build Status: **SUCCESS**
- Build URL: [Nordix Jenkins](https://jenkins.nordix.org/job/etos-environment-provider-build-merge-ubuntu2004-main/16/)
- Command to pull image:
    `docker pull registry.nordix.org/eiffel/etos-environment-provider:dev`
    or
    `podman pull registry.nordix.org/eiffel/etos-environment-provider:dev`

**Pull request merged**
