### PR TITLE
Decouple the sub suite endpoint for clarity

### PR DESCRIPTION
**Pull request by t-persson**
### Applicable Issues

eiffel-community/etos#83

### Description of the Change

This PR is the first of several clean-up changes that will be created. I do them in steps to make reviewing easier.

This is done in preparation for the external provider change that is on its way ( #38 )
By making the endpoints cleaner, we can make the external provider changes easier.

### Alternate Designs

There are multiple designs, I chose the one where we

1. Reduce the size of webserver.py the most.
2. Make it easier to test.

### Benefits

Makes it easier to understand what is going on in the webserver.py file and makes it a lot easier to test.

### Possible Drawbacks

Some code-jumping will be involved. With proper function naming this will be mitigated.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

### CODE REVIEW

**Comment by t-persson** [comment]
Changed this to two commits so I can reuse the database change in other PRs :)

**Comment by t-persson** [comment]
> Changed this to two commits so I can reuse the database change in other PRs :)

I will split out the test helpers as well..

**Comment by t-persson** [comment]
Sorry for the spam. Should not need any more updates now

**Review by andjoe-axis — APPROVED** [review]

**Review by fredjn — APPROVED** [review]

**Review by nordixinfra — COMMENTED** [review]
- Build Status: **SUCCESS**
- Build URL: [Nordix Jenkins](https://jenkins.nordix.org/job/etos-environment-provider-build-merge-ubuntu2004-main/6/)
- Command to pull image:
    `docker pull registry.nordix.org/eiffel/etos-environment-provider:dev`
    or
    `podman pull registry.nordix.org/eiffel/etos-environment-provider:dev`

**Review by nordixinfra — COMMENTED** [review]
- Build Status: **SUCCESS**
- Build URL: [Nordix Jenkins](https://jenkins.nordix.org/job/etos-environment-provider-build-merge-ubuntu2004-main/7/)
- Command to pull image:
    `docker pull registry.nordix.org/eiffel/etos-environment-provider:dev`
    or
    `podman pull registry.nordix.org/eiffel/etos-environment-provider:dev`

**Pull request merged**
